/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.reldb.dbLogger.tests;

import org.junit.jupiter.api.Test;

import org.reldb.dbLogger.Log;
import org.reldb.dbLogger.SQLiteDatabase;

import java.util.TreeMap;

class SQLiteDatabaseTest {
    @Test void testLogBasic() {
        try (var db = new SQLiteDatabase("./testdb.sqlite")) {
            var log = new Log(db.getConnection(), "testlog");
            var map = new TreeMap<String, Object>();
            for (int i = 0; i < 10; i++) {
                map.put("a", i);
                map.put("b", "" + i);
                map.put("c", "blah");
                log.insert(map);
            }
            for (int i = 11; i < 20; i++) {
                map.put("a", i);
                map.put("b", "" + i);
                map.put("c", "blah");
                map.put("d", (float) i);
                log.insert(map);
            }
        }
    }
}
