/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.reldb.dbLogger.tests;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import org.reldb.dbLogger.Log;
import org.reldb.dbLogger.SQLiteDatabase;
import org.reldb.dbLogger.Logger;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.List;

class SQLiteDatabaseTest {

    private static final String LOGDBFILENAME = "./testdb.sqlite";

    @BeforeAll static void startup() throws IOException {
        Files.deleteIfExists(Path.of(LOGDBFILENAME));
    }

    @Test void testLogBasic() throws SQLException {
        try (var db = new SQLiteDatabase(LOGDBFILENAME)) {
            try (var log = new Log(db.getConnection(), "testlog")) {
                for (int i = 0; i < 10; i++) {
                    Logger.log("a", i)
                            .log("b", "" + i)
                            .log("c", "blah")
                            .insert(log);
                }
                for (int i = 11; i < 20; i++) {
                    Logger.log("a", i)
                            .log("b", "" + i)
                            .log("c", "blah")
                            .log("d", (float) i)
                            .insert(log);
                }
            }
        }
    }

    @Test void testLogNested() throws SQLException {
        try (var db = new SQLiteDatabase(LOGDBFILENAME)) {
            try (var log = new Log(db.getConnection(), "testlognested")) {
                for (int i = 0; i < 10; i++) {
                    Logger.log("a", i)
                            .log("b", "" + i)
                            .log("c", "blah")
                            .log("n", Logger.log("p", i * 10)
                                    .log("q", (double) (i * 20))
                                    .log("a", i + 100))
                            .insert(log);
                }
            }
        }
    }

    @Test void testLogList() throws SQLException {
        try (var db = new SQLiteDatabase(LOGDBFILENAME)) {
            try (var log = new Log(db.getConnection(), "testloglist")) {
                for (int i = 0; i < 10; i++) {
                    List<Object> testlist = new LinkedList<>();
                    testlist.add(3);
                    testlist.add(5.2);
                    testlist.add("7");
                    Logger.log("a", i)
                            .log("b", "" + i)
                            .log("c", testlist)
                            .log("n", Logger.log("p", i * 10)
                                    .log("q", testlist)
                                    .log("a", i + 100))
                            .insert(log);
                }
            }
        }
    }

}
